### ISSUE TITLE
Conflict with React-hot-loader

### ISSUE THREAD

**Issue by HZSamir** [salman3k1/redux-action-watcher#1]
Hello,
When used in conjunction with react-hot-loader this module throws the following error on file save:

```
/node_modules/redux-action-watcher/lib/index.js:1 Uncaught RangeError: Maximum call stack size exceeded
    at StateWatcher.e.componentWillUnmount [as originalComponentWillUnmount]
```
How to fix it?
Thank you.

**Comment by salman3k1** [comment]
Can you please share the version of react-hot-loader you are using? I have tested it with ^4.8.0 and its working fine for me. Or maybe share a working example to reproduce the issue?

**Comment by salman3k1** [comment]
Well what I was doing for user's convenience was to extend the componentWillUnmount hook. I have given it a thought and it might conflict with other packages as well in the future if I carry it this way. So I think its better to handover the control to the user. I have done some refactoring and published a new version. You can fetch the new one and in your componentWillUnmount method use this.unsubscribeFromWatcher() to manually unsubscribe(Please refer to README.md for an example). Hope that helps.

**Comment by HZSamir** [comment]
It is perfect now. Thank you for the fix and this amazing package.
